FROM tomcat:8.5

WORKDIR /usr/local/tomcat

RUN chmod -R 777 /usr/local/tomcat && \
    mkdir /usr/local/tomcat/webapps/judice && \
    apt-get clean && apt-get update && apt-get install -y locales && \
    locale-gen pt_BR.UTF-8 && \
    localedef -i pt_BR -c -f UTF-8 -A /usr/share/locale/locale.alias pt_BR.utf-8

ENV LANG pt_BR.UTF-8

ENV LANGUAGE pt_BR:pt:en

ENV LC_ALL pt_BR.UTF-8